jhipster-dev-postgresql:
  container_name: angularSpringAttempt3-dev-postgresql
  image: postgres:9.4.5
  # volumes:
  # - ~/volumes/jhipster/angularSpringAttempt3/dev-postgresql/:/var/lib/postgresql/
  environment:
  - POSTGRES_USER=angularSpringAttempt3
  - POSTGRES_PASSWORD=
  ports:
  - "5432:5432"

